pgm :: avail_set.o backtrack.o kempe.o res.o sat_ops.o shuffle.o single_wander.o smallest_last.o sparse_class.o static_ops.o urand.o ; cc -O4 -f68881 avail_set.o backtrack.o kempe.o res.o sat_ops.o shuffle.o single_wander.o smallest_last.o sparse_class.o static_ops.o urand.o -lm -o res
.c.o: ; cc -c -O4 -f68881 -o $@ $*.c
avail_set.o :
backtrack.o :
kempe.o :
res.o :
sat_ops.o :
shuffle.o :
single_wander.o :
smallest_last.o :
sparse_class.o :
static_ops.o :
urand.o : 
